### ISSUE TITLE
GameSolver break on small upperBound

### ISSUE THREAD

**Issue by chinnonae** [OOP2018/guessing-game-thanakritfluk#1]
Try small upperbound like `2`

**Comment by thanakritfluk** [comment]
@chinnonae please check my code again.

**Comment by chinnonae** [comment]
I used `upperBound = 3` and it's still break

![image](https://user-images.githubusercontent.com/11190475/35140716-e1013da6-fd2a-11e7-8009-1f892c9e168c.png)

**Comment by thanakritfluk** [comment]
I fixed it already pls check it again.
